#version 460

#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

layout(local_size_x = 1024) in;

struct Particle {
    float px, py, pz;
    float vx, vy, vz;
    float ttl;
    float size;
    uint8_t r, g, b, a;
};

layout(std430, binding = 0) buffer ParticlesBuffer { Particle particles[]; };
layout(std430, binding = 1) buffer SortedIndices { uint16_t indices[]; };

layout(push_constant) uniform PushConstants {
    mat4 globalToScreen;
} push;

shared uint localIndices[1024];
shared float localDepths[1024];

void main() {
    uint idx = gl_LocalInvocationID.x;
    localIndices[idx] = indices[idx];
    uint16_t pIdx = indices[idx];
    float depth = -100000.0;
    if (pIdx < particles.length()) {
        if (particles[pIdx].ttl > 0.0) {
            vec4 pos = push.globalToScreen * vec4(particles[pIdx].px, particles[pIdx].py, particles[pIdx].pz, 1.0);
            depth = pos.z / pos.w; 
        } else {
            depth = 100000.0; 
        }
    }
    localDepths[idx] = depth;
    barrier();
    for (uint k = 2; k <= 1024; k <<= 1) {
        for (uint j = k >> 1; j > 0; j >>= 1) {
            uint ixj = idx ^ j;
            if (ixj > idx) {
                bool descending = bool((idx & k) == 0);
                float d1 = localDepths[idx];
                float d2 = localDepths[ixj];
                bool swap = descending ? bool(d1 < d2) : bool(d1 > d2);
                if (swap) {
                    localDepths[idx] = d2;
                    localDepths[ixj] = d1;
                    uint tmpIdx = localIndices[idx];
                    localIndices[idx] = localIndices[ixj];
                    localIndices[ixj] = tmpIdx;
                }
            }
            barrier();
        }
    }
    indices[idx] = uint16_t(localIndices[idx]);
}
